"""Document safety: quarantined passages and processing warnings

Revision ID: a3604f973e34
Revises: ee1776212641
Create Date: 2026-09-26 16:24:46.230941
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a3604f973e34'
down_revision: str | None = 'ee1776212641'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('flagged', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('document_versions', sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'warnings')
    op.drop_column('chunks', 'flagged')
    # ### end Alembic commands ###
