"""validation review and duplicates

Revision ID: c3882f2cb122
Revises: 7a462efd9c1f
Create Date: 2026-09-26 09:42:45.646414
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c3882f2cb122'
down_revision: str | None = '7a462efd9c1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_runs',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('python_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_validation_runs_analysis_run_id_analysis_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_validation_runs_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_runs'))
    )
    op.create_index(op.f('ix_validation_runs_complaint_id'), 'validation_runs', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_created_at'), 'validation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_validation_runs_verdict'), 'validation_runs', ['verdict'], unique=False)
    op.create_table('review_tasks',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('validation_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_review_tasks_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_review_tasks_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_review_tasks_resolved_by_id_users')),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_review_tasks_validation_run_id_validation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index(op.f('ix_review_tasks_complaint_id'), 'review_tasks', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_created_at'), 'review_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('reviewer_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('review_task_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_reviewer_decisions_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], name=op.f('fk_reviewer_decisions_review_task_id_review_tasks')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviewer_decisions_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer_decisions'))
    )
    op.create_index(op.f('ix_reviewer_decisions_complaint_id'), 'reviewer_decisions', ['complaint_id'], unique=False)
    op.add_column('complaints', sa.Column('duplicate_of_id', sa.Uuid(), nullable=True))
    op.add_column('complaints', sa.Column('related_complaint_id', sa.Uuid(), nullable=True))
    op.add_column('complaints', sa.Column('similarity', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('complaints', sa.Column('supporting_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('complaints', sa.Column('verification', sa.String(length=20), nullable=True))
    op.add_column('complaints', sa.Column('approved_response', sa.Text(), nullable=True))
    op.create_index(op.f('ix_complaints_verification'), 'complaints', ['verification'], unique=False)
    op.create_foreign_key(op.f('fk_complaints_duplicate_of_id_complaints'), 'complaints', 'complaints', ['duplicate_of_id'], ['id'])
    op.create_foreign_key(op.f('fk_complaints_related_complaint_id_complaints'), 'complaints', 'complaints', ['related_complaint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_complaints_related_complaint_id_complaints'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('fk_complaints_duplicate_of_id_complaints'), 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_verification'), table_name='complaints')
    op.drop_column('complaints', 'approved_response')
    op.drop_column('complaints', 'verification')
    op.drop_column('complaints', 'supporting_departments')
    op.drop_column('complaints', 'embedding')
    op.drop_column('complaints', 'similarity')
    op.drop_column('complaints', 'related_complaint_id')
    op.drop_column('complaints', 'duplicate_of_id')
    op.drop_index(op.f('ix_reviewer_decisions_complaint_id'), table_name='reviewer_decisions')
    op.drop_table('reviewer_decisions')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_created_at'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_complaint_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_validation_runs_verdict'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_created_at'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_complaint_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    # ### end Alembic commands ###
