"""import batches

Revision ID: ebc044fd7154
Revises: cd121c6c5f84
Create Date: 2026-09-27 17:08:09.082163
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ebc044fd7154'
down_revision: str | None = 'cd121c6c5f84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_import_batches_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_sha256'), 'import_batches', ['sha256'], unique=False)
    op.add_column('complaints', sa.Column('import_batch_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_complaints_import_batch_id'), 'complaints', ['import_batch_id'], unique=False)
    op.create_foreign_key(op.f('fk_complaints_import_batch_id_import_batches'), 'complaints', 'import_batches', ['import_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_complaints_import_batch_id_import_batches'), 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_import_batch_id'), table_name='complaints')
    op.drop_column('complaints', 'import_batch_id')
    op.drop_index(op.f('ix_import_batches_sha256'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
