"""complaint attachments

Revision ID: e96c4ce1c2d4
Revises: ef4cc7330a25
Create Date: 2026-09-27 15:16:11.706384
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = 'e96c4ce1c2d4'
down_revision: str | None = 'ef4cc7330a25'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_attachments',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('media_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_attachments_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_complaint_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_attachments'))
    )
    op.create_index(op.f('ix_complaint_attachments_complaint_id'), 'complaint_attachments', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_attachments_complaint_id'), table_name='complaint_attachments')
    op.drop_table('complaint_attachments')
    # ### end Alembic commands ###
