"""SLA tracking: deadlines, first response, resolution time and SLA status

Revision ID: ee1776212641
Revises: c3882f2cb122
Create Date: 2026-09-26 15:50:10.514511
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ee1776212641'
down_revision: str | None = 'c3882f2cb122'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('first_response_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('sla_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.create_index(op.f('ix_complaints_sla_status'), 'complaints', ['sla_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_sla_status'), table_name='complaints')
    op.drop_column('complaints', 'sla_status')
    op.drop_column('complaints', 'resolved_at')
    op.drop_column('complaints', 'first_responded_at')
    op.drop_column('complaints', 'resolution_due_at')
    op.drop_column('complaints', 'first_response_due_at')
    # ### end Alembic commands ###
