"""Orders lifecycle

Revision ID: f8f9688aefa2
Revises: edd96d9ded2e
Create Date: 2026-09-29 10:16:02.984888
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f8f9688aefa2'
down_revision: str | None = 'edd96d9ded2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('currency', name=op.f('pk_fx_rates'))
    )
    op.create_table('order_events',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=10), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_order_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('stage', sa.String(length=24), server_default='placed', nullable=False))
    op.add_column('orders', sa.Column('next_step_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('manual_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('emails_sent', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('orders', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('orders', sa.Column('fx_rate', sa.Numeric(precision=14, scale=6), server_default='1', nullable=False))
    op.add_column('orders', sa.Column('amount_local', sa.Numeric(precision=14, scale=2), nullable=True))
    op.create_index(op.f('ix_orders_next_step_at'), 'orders', ['next_step_at'], unique=False)
    op.add_column('outbound_emails', sa.Column('order_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_outbound_emails_order_id'), 'outbound_emails', ['order_id'], unique=False)
    op.create_foreign_key(op.f('fk_outbound_emails_order_id_orders'), 'outbound_emails', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
    # Existing orders get the stage that mirrors their status; they never advance.
    op.execute(
        "UPDATE orders SET stage = CASE status WHEN 'processing' THEN 'placed' "
        "WHEN 'shipped' THEN 'shipped' WHEN 'in_transit' THEN 'shipped' WHEN 'lost' THEN 'lost' "
        "WHEN 'returned' THEN 'returned' WHEN 'cancelled' THEN 'cancelled' "
        "ELSE 'delivered' END, amount_local = amount"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_outbound_emails_order_id_orders'), 'outbound_emails', type_='foreignkey')
    op.drop_index(op.f('ix_outbound_emails_order_id'), table_name='outbound_emails')
    op.drop_column('outbound_emails', 'order_id')
    op.drop_index(op.f('ix_orders_next_step_at'), table_name='orders')
    op.drop_column('orders', 'amount_local')
    op.drop_column('orders', 'fx_rate')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'emails_sent')
    op.drop_column('orders', 'expected_delivery_date')
    op.drop_column('orders', 'manual_hold')
    op.drop_column('orders', 'next_step_at')
    op.drop_column('orders', 'stage')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
