"""App settings and job runs

Revision ID: edd96d9ded2e
Revises: ebc044fd7154
Create Date: 2026-09-28 22:31:59.645858
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'edd96d9ded2e'
down_revision: str | None = 'ebc044fd7154'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('job', sa.String(length=60), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job', name=op.f('pk_job_runs'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
