"""complaints analysis and rules

Revision ID: 7a462efd9c1f
Revises: fa857498bf68
Create Date: 2026-09-26 09:22:25.870924
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7a462efd9c1f'
down_revision: str | None = 'fa857498bf68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Sequences behind CMP-000123 / CUST-000045 reference numbers.
    op.execute("CREATE SEQUENCE IF NOT EXISTS complaint_ref_seq")
    op.execute("CREATE SEQUENCE IF NOT EXISTS customer_ref_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('sha256', name=op.f('uq_prompt_versions_sha256'))
    )
    op.create_table('rules',
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('supporting_departments', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('required_actions', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('prohibited_actions', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('policy_refs', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('follow_up_type', sa.String(length=40), nullable=True),
    sa.Column('follow_up_hours', sa.Integer(), nullable=True),
    sa.Column('rule_priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    sa.UniqueConstraint('rule_id', name=op.f('uq_rules_rule_id'))
    )
    op.create_index(op.f('ix_rules_category'), 'rules', ['category'], unique=False)
    op.create_index(op.f('ix_rules_rule_type'), 'rules', ['rule_type'], unique=False)
    op.create_table('customers',
    sa.Column('customer_ref', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('customer_ref', name=op.f('uq_customers_customer_ref')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customers_user_id'))
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('orders',
    sa.Column('order_ref', sa.String(length=20), nullable=False),
    sa.Column('transaction_ref', sa.String(length=24), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_method', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('committed_delivery_date', sa.Date(), nullable=False),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_ref', name=op.f('uq_orders_order_ref')),
    sa.UniqueConstraint('transaction_ref', name=op.f('uq_orders_transaction_ref'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_ref', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('product_service', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('preferred_contact_channel', sa.String(length=20), nullable=True),
    sa.Column('requested_resolution', sa.Text(), nullable=True),
    sa.Column('previous_complaint_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intake_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_code', sa.String(length=40), nullable=True),
    sa.Column('subcategory_code', sa.String(length=60), nullable=True),
    sa.Column('department_code', sa.String(length=40), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_complaints_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_complaints_order_id_orders')),
    sa.ForeignKeyConstraint(['previous_complaint_id'], ['complaints.id'], name=op.f('fk_complaints_previous_complaint_id_complaints')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_complaints_submitted_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints')),
    sa.UniqueConstraint('complaint_ref', name=op.f('uq_complaints_complaint_ref'))
    )
    op.create_index(op.f('ix_complaints_category_code'), 'complaints', ['category_code'], unique=False)
    op.create_index('ix_complaints_customer_hash', 'complaints', ['customer_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_department_code'), 'complaints', ['department_code'], unique=False)
    op.create_index(op.f('ix_complaints_external_ref'), 'complaints', ['external_ref'], unique=False)
    op.create_index(op.f('ix_complaints_needs_review'), 'complaints', ['needs_review'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('schema_version', sa.String(length=60), nullable=True),
    sa.Column('retrieved_policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_analysis_runs_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_analysis_runs_prompt_version_id_prompt_versions')),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_analysis_runs_triggered_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_complaint_id'), 'analysis_runs', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    op.create_table('complaint_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('customer_visible', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_complaint_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_events_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_events'))
    )
    op.create_index(op.f('ix_complaint_events_complaint_id'), 'complaint_events', ['complaint_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_llm_calls_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index(op.f('ix_llm_calls_analysis_run_id'), 'llm_calls', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_calls_analysis_run_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_complaint_events_complaint_id'), table_name='complaint_events')
    op.drop_table('complaint_events')
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_complaint_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_needs_review'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_external_ref'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_department_code'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_index('ix_complaints_customer_hash', table_name='complaints')
    op.drop_index(op.f('ix_complaints_category_code'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_rules_rule_type'), table_name='rules')
    op.drop_index(op.f('ix_rules_category'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS customer_ref_seq")
    op.execute("DROP SEQUENCE IF EXISTS complaint_ref_seq")
