"""email channel

Revision ID: cd121c6c5f84
Revises: e96c4ce1c2d4
Create Date: 2026-09-27 15:22:18.306582
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = 'cd121c6c5f84'
down_revision: str | None = 'e96c4ce1c2d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailbox_state'))
    )
    op.create_table('inbound_emails',
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('complaint_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('via', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_inbound_emails_complaint_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_emails')),
    sa.UniqueConstraint('message_id', name=op.f('uq_inbound_emails_message_id'))
    )
    op.create_index(op.f('ix_inbound_emails_complaint_id'), 'inbound_emails', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_inbound_emails_outcome'), 'inbound_emails', ['outcome'], unique=False)
    op.create_table('outbound_emails',
    sa.Column('complaint_id', sa.Uuid(), nullable=True),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('in_reply_to', sa.String(length=300), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_outbound_emails_complaint_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_emails')),
    sa.UniqueConstraint('message_id', name=op.f('uq_outbound_emails_message_id'))
    )
    op.create_index(op.f('ix_outbound_emails_complaint_id'), 'outbound_emails', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_outbound_emails_status'), 'outbound_emails', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_emails_status'), table_name='outbound_emails')
    op.drop_index(op.f('ix_outbound_emails_complaint_id'), table_name='outbound_emails')
    op.drop_table('outbound_emails')
    op.drop_index(op.f('ix_inbound_emails_outcome'), table_name='inbound_emails')
    op.drop_index(op.f('ix_inbound_emails_complaint_id'), table_name='inbound_emails')
    op.drop_table('inbound_emails')
    op.drop_table('mailbox_state')
    # ### end Alembic commands ###
